matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script: 
  - git clone https://github.com/meganrenae21/life-bingo.git
  - cd life-bingo
  - npm install
  - npm run test
